# Generated by Django 4.0.4 on 2022-05-10 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mothership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('capacity', models.SmallIntegerField(default=9)),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('capacity', models.SmallIntegerField(default=5)),
                ('mothership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mothership')),
            ],
        ),
        migrations.CreateModel(
            name='ShipCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.crewmember')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ship')),
            ],
        ),
        migrations.AddField(
            model_name='crewmember',
            name='ship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ship'),
        ),
    ]
